name: Build Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.15.0
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm exec nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.15.0
    with:
      number-of-agents: 3

  e2e:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: oven-sh/setup-bun@v2
        name: setup bun

      - uses: pnpm/action-setup@v3
        name: Install pnpm

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Build ts-rest libs'
        run: 'pnpm exec nx run-many --target=build --projects="ts-rest*"'

      - name: 'E2E Tests 🧪'
        run: make e2e
