name: Build Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Test'
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: NX Affected
        run: pnpm nx affected -t lint test build --code-coverage

  e2e:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: oven-sh/setup-bun@v2
        name: setup bun

      - uses: pnpm/action-setup@v3
        name: Install pnpm

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Build ts-rest libs'
        run: 'pnpm exec nx run-many --target=build --projects="ts-rest*"'

      - name: 'E2E Tests 🧪'
        run: make e2e
