name: Release
on:
  push:
    branches:
      - main

jobs:
  get-next-version:
    if: ${{ hashFiles('.changeset/[!.*][!README]*.md') != '' }}
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.new-version.outputs.current-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm version-packages
      - uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b
        id: new-version
        with:
          path: packages/core/package.json

  build-and-release:
    needs: get-next-version
    if: ${{ !failure() && !canceled() }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get release version
        id: release-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b
        with:
          path: packages/core

      - name: Modify "workspaces" value in package.json
        run: sed -i -e "s;packages/\*;dist/packages/*;g" package.json

      - name: Create Release Pull Request or Publish to npm
        uses: dotansimha/changesets-action@069996e9be15531bd598272996fa23853d61590e
        with:
          title: |
            ${{ needs.get-next-version.outputs.new-version && format('release: v{0}', needs.get-next-version.outputs.new-version) || null }}
          commit: |
            ${{ needs.get-next-version.outputs.new-version && format('release: v{0}', needs.get-next-version.outputs.new-version) || null }}
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          version: pnpm version-packages
          createGithubReleases: aggregate
          githubReleaseName: v${{ steps.release-version.outputs.current-version }}
          githubTagName: v${{ steps.release-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
